"""Inicializando bd

Revision ID: 7e6461cf1041
Revises: 
Create Date: 2025-05-18 21:55:27.741286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6461cf1041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=80), nullable=False),
    sa.Column('apellidoUsiario', sa.String(length=80), nullable=False),
    sa.Column('cargoUsuario', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
