"""Inicializando bd

Revision ID: cc4f0daaac95
Revises: 7e6461cf1041
Create Date: 2025-05-18 21:57:12.925277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4f0daaac95'
down_revision = '7e6461cf1041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('idSensor', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Integer(), nullable=False),
    sa.Column('encendido', sa.Boolean(), nullable=False),
    sa.Column('ubicacion', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('idSensor')
    )
    op.create_table('servidor',
    sa.Column('idServidor', sa.Integer(), nullable=False),
    sa.Column('ServidorActivo', sa.Boolean(), nullable=False),
    sa.Column('tempMaXCelsius', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('idServidor')
    )
    op.create_table('sistema_enfriamiento',
    sa.Column('idSE', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idSE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sistema_enfriamiento')
    op.drop_table('servidor')
    op.drop_table('sensor')
    # ### end Alembic commands ###
