"""tabla temperatura

Revision ID: cf334dcac19a
Revises: 
Create Date: 2025-05-23 22:01:50.322880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf334dcac19a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('codigo_ubicacion', sa.String(length=100), nullable=False),
    sa.Column('temperatura_maxima_celsius', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=80), nullable=False),
    sa.Column('apellidoUsuario', sa.String(length=80), nullable=False),
    sa.Column('cargoUsuario', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('temperatura')
    op.drop_table('servidor')
    # ### end Alembic commands ###
